# Generated by Django 5.1.1 on 2024-10-09 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя артиста')),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('hip_hop', 'Hip hop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('country', 'Country'), ('electronic', 'Electronic'), ('reggae', 'Reggae'), ('blues', 'Blues'), ('metal', 'Metal'), ('r_b', 'R&B'), ('alternative', 'Alternative'), ('folk', 'Folk'), ('indie', 'Indie'), ('punk', 'Punk'), ('disco', 'Disco'), ('latin', 'Latin'), ('other', 'Other')], default='other', max_length=255, verbose_name='Жанр')),
                ('most_popular_track', models.CharField(max_length=255, verbose_name='Самый популярный трек')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название альбома')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('artists', models.ManyToManyField(related_name='album_tracks', to='music.artist')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название трека')),
                ('duration', models.DurationField(verbose_name='Длительность')),
                ('audio', models.FileField(upload_to='tracks/', verbose_name='Аудиофайл')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('explicit', models.BooleanField(default=False, verbose_name='Содержит нецензурные слова')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.album', verbose_name='Альбом')),
                ('artists', models.ManyToManyField(related_name='track_artist', to='music.artist')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электроная почта')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('following_artists', models.ManyToManyField(blank=True, related_name='followerslist', to='music.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название плейлиста')),
                ('tracks', models.ManyToManyField(related_name='playlists', to='music.track', verbose_name='Треки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followingartists', to='music.user'),
        ),
    ]
